#cloud-config
#Only values to be inserted are token and cluster name. Insert as is without parenthesis
write_files:
#ves
- path: /etc/hosts
  content: |
    # IPv4 and IPv6 localhost aliases
    127.0.0.1         localhost
    ::1               localhost
    127.0.1.1         vip
    169.254.169.254   metadata.google.internal
  permissions: 0644
  owner: root
- path: /etc/vpm/config.yaml
  permissions: 0644
  owner: root
  content: |
    Vpm:
      ClusterName: #### TO BE REPLACED WITH CLUSTER NAME #### 
      ClusterType: ce
      Token: #### TO BE REPLACED BY F5XC API TOKEN ####
      MauricePrivateEndpoint: https://register-tls.ves.volterra.io
      MauriceEndpoint: https://register.ves.volterra.io
      CertifiedHardwareEndpoint: https://vesio.blob.core.windows.net/releases/certified-hardware/gcp.yml
    Kubernetes:
      EtcdUseTLS: True
      Server: vip